### ISSUE TITLE
WoWUp can't find the addon

### ISSUE THREAD

**Issue by mathwro** [BigWigsMods/BigWigs_Cataclysm#14]
Hi,
Seemingly something is different just for BigWigs_Cataclysm as WoWUp CF is not able to find this addon, but i can see every other addon

![image](https://github.com/BigWigsMods/BigWigs_Cataclysm/assets/16838008/3178abd5-e091-4e23-a3fc-489cae441fce)

**Comment by funkydude** [comment]
This isn't really a BigWigs issue. But I told the WoWUp Devs and they said they'll release a new update with a fix for not detecting all Cataclysm addons (wasn't just an issue for us).
