### ISSUE TITLE
Missing spell on Alysrazor (H25) in Firelands

### ISSUE THREAD

**Issue by Xerus2** [BigWigsMods/BigWigs_Cataclysm#7]
1x Found spell 'Wings of Flame' using id 98619 on 6, tell the authors!
BigWigs_Core\BossPrototype.lua:1055: in function `UnitBuff'
...aceBigWigs_Cataclysm\Firelands\Alysrazor.lua:135: in function `?'
BigWigs_Core\BossPrototype.lua:503: in function <BigWigs_Core\BossPrototype.lua:498>

Locals:
InCombatSkipped

**Comment by funkydude** [comment]
This seems to have already been fixed in https://github.com/BigWigsMods/BigWigs_Cataclysm/commit/0f44f389ec4e0d8add7fe163cd1f289e581870bb before this issue was created.
